### PR TITLE
Preprint remodel model changes

### PR DESCRIPTION
**Pull request by tingletech**
adds a `preprint_doi` to the `Preprints` model

add a `PreprintSupplementaryFile` model

### CODE REVIEW

**Comment by Bbkctp** [comment]
Can one of the admins verify this patch?

**Comment by ajrbyers** [comment]
test this please

**Comment by ajrbyers** [comment]
@tingletech do you want me to add the migration?

**Comment by tingletech** [comment]
I don't know re: `makemigration` -- your call -- if I run that I get migrations that are not related to this commit.

**Pull request merged**
