### PR TITLE
Light copyedits

### PR DESCRIPTION
**Pull request by joemull**
Made these light edits while comparing the documentation content to the behavior of the 1.4.1 interface.

### CODE REVIEW

**Review by hardyoyo — APPROVED** [review]
👍 obviously correct copy edits

**Comment by hardyoyo** [comment]
I think a bunch of commits got pulled in to this branch by mistake?

**Comment by joemull** [comment]
Hi @hardyoyo , sorry about the messy commit history--I rebased this branch onto the latest "master", which has the effect of committing everything that has happened on "master" from when the branch was originally created up to now. I might scrap this branch and start a new one, though, as we are discussing whether to convert the end-user documentation to pure markdown at the same time as I do light copyedits. I will check with Andy and Mauro.

**Comment by joemull** [comment]
Now that I know more about our desired behavior for `git rebase`, I can see this is not what we want. Closing!

**Pull request closed without merging**
