### PR TITLE
Adds a new setting to conceal the editor details when an author is viewing their article's metadata.

### LINKED ISSUE #3738: Switch to conceal editors' names so authors cannot see who has been assigned to look after their submission
**Is your feature request related to a problem? Please describe.**
As things stand, authors are able to find out which member of the editorial team has been assigned to “look after” their submission (i.e. give it a preliminary assessment and, if it is deemed good enough to go out for review, administer this process).  This is undesirable because our research community is small and we need to protect the identity of the individual to avoid potential bad blood and to ensure that our editors can do as they see fit (e.g. reject an article) without fear of repercussions.
 
**Describe the solution you'd like**
We’d like there to be a switch at the journal level that enables us to conceal the editors’ names that authors can currently see.  It would also be good to be able to switch this on or off at the level of an individual paper, in case we decide to change our policy in future but find it necessary to conceal editors’ identities from time to time.
 
**Describe alternatives you've considered**
N/A
 
**Additional context**

### PR DESCRIPTION
**Pull request by ajrbyers**
I believe this solution covers most of the request in #3738, as Phillipa is talking about the editors section of the article metadata page. However, in discussion with @mauromsl we noted that an editor may still reveal themselves when rejecting a paper as their email address will be used in the reply-to section.

There is some discussion to be had about how we approach this, do we want to enable the anonymous rejection of papers easily? The public display of an editorial board means that either way this is only partially anonymous as an author will be aware of who the editors are generally.

Personally I think this solution is enough, as editor should be accountable for article decisions, if editors _do_ want to circumvent the reply-to setup they could make use of a generic account to desk reject papers. Open to thoughts on this one. I've assigned everyone as a review so we can chip in our two cents.

Potentially closes #3738 

For clarification this page is accessed by authors from the Dashboard (Dashboard > Active Articles > View Status) screenshots with and without edutor details below.

Without editor details:
Screenshot 2024-03-12 at 17 17 05

With editor details:
Screenshot 2024-03-12 at 17 16 51

### CODE REVIEW

**Comment by joemull** [comment]
@ajrbyers If you've got this one running with an example, would you mind throwing a screenshot on this PR so people can see what screen the change would be on?

**Review by joemull — CHANGES_REQUESTED** [review]
OK, this is pretty good.

I am OK with the email address solution you propose if the editors are.

One visibility logic thing I'd rather see changed is how this includes `user_is_editor` as an override. If I am an editor viewing this page, I will see the editors listed, even if the hide setting is on. This will lead me to question whether the setting is working, because I have no way to verify that the author sees something different from me. 

So, I'd suggest adding some explanatory text explaining to editors that authors cannot see the list of editors. This template is re-used in several places, some author-facing and some internal. So the text would need to work in both contexts.

BTW, this was an interesting thing for me to think through, because it goes back to the theme that came out of the copyediting UX research: "seeing what others can see" is often a pickle in Janeway. A good future candidate for a re-usable design element explaining the role visibility of a given thing.

**Comment by ajrbyers** [comment]
@joemull 

> So, I'd suggest adding some explanatory text explaining to editors that authors cannot see the list of editors. This template is re-used in several places, some author-facing and some internal. So the text would need to work in both contexts.

How about wrapping the explanitory note in `{% if user_is_editor %}` so that the author doesn't have to see it?

**Comment by joemull** [comment]
> How about wrapping the explanitory note in `{% if user_is_editor %}` so that the author doesn't have to see it?

Yes that's what I was imagining!

**Comment by joemull** [comment]
@ajrbyers errr, actually, the visibility info text would need to be based on `{% if journal_settings.general.hide_editors_from_authors %}`, not role-based. Authors then won't ever see it, because the outer check would hide the whole thing from them.

**Comment by ajrbyers** [comment]
> @ajrbyers errr, actually, the visibility info text would need to be based on `{% if journal_settings.general.hide_editors_from_authors %}`, not role-based. Authors then won't ever see it, because the outer check would hide the whole thing from them.

As it turns out, its both. Anyway, commit is in.

**Review by S-Haime — APPROVED** [review]
I think this sounds good as a solution, as long as we (I) document it precisely enough and make clear when what information is visible so editors can make an informed decision. I see merit in being able to fully anonymously do desk rejects in certain fields (youch!) through a generic account, but I feel like this is not a common request.

**Review by joemull — APPROVED** [review]

**Review by mauromsl — APPROVED** [review]

**Pull request merged**
