### PR TITLE
Account Institution made optional

### PR DESCRIPTION
**Pull request by mdlincoln**
Is there a strong reason why `Institution` is the only required field for user accounts besides email, pw, and name? We've had a couple of our testers remark (correctly, I think!) that this is not a desirable message to send in the modern academic world.

### CODE REVIEW

**Comment by Bbkctp** [comment]
Can one of the admins verify this patch?

**Comment by mauromsl** [comment]
add to whitelist

**Comment by ajrbyers** [comment]
@mdlincoln we’re discussing this at the moment. That said, if the premise of the change is accepted there are a bunch of instances that will need to be handled for an empty Institution field throughout the codebase.

**Comment by ajrbyers** [comment]
We're all on board with making institution an optional field, however, as mentioned above we need to add handlers for this throughout the codebase especially for the front end so that Institution doesn't show up as `None`.

**Pull request closed without merging**
