### PR TITLE
add return url to file upload in document management

### PR DESCRIPTION
**Pull request by hachacha**
place return url as hidden input in upload form. change redirect to have the return var as GET.

pr for https://github.com/BirkbeckCTP/janeway/issues/980

### CODE REVIEW

**Comment by hachacha** [comment]
Yeah, you're right, the return_url does not need to be placed in the form at all since it's already in the GET. 
Good eyes!
I wonder about the delete buttons though,
`<a href="{% url 'article_file_replace' 'id' article.pk file.pk %}?return={{ request.path|urlencode }}%3Freturn%3D{{ request.GET.return|urlencode }}"><i
                                    class="fa fa-cloud-upload">&nbsp;</i></a>` 

`journal_name/11/files/92/delete/?return=/journal_name/production/11/`
and if they should have the return_url on them, because this brings you out of document_management when you may not be done managing documents.

**Comment by hachacha** [comment]
Our Janeway user on the production server just ran in to this issue of getting bounced to the press-level /dashboard after clicking `return` on the files management page. Any chance this could get reviewed soon?

**Comment by ajrbyers** [comment]
@hachacha happy to merge this, but you made come comments about the other buttons and I assumed you were looking into that issue?

**Comment by hachacha** [comment]
Alright I just updated the delete button so that you return to the file manager and not the article on deletion.
This is all I wanted to merge :)

**Pull request merged**
