### PR TITLE
Fix migration order error

### PR DESCRIPTION
**Pull request by yakky**
There is a migration order mismatch on `master`

### CODE REVIEW

**Comment by Bbkctp** [comment]
Can one of the admins verify this patch?

**Comment by ajrbyers** [comment]
Thanks @yakky. This is happening more and more where branches are merged and we’ve been discussing how to mitigate. 

Jenkins: test this please

**Comment by yakky** [comment]
@ajrbyers probably adding `python src/manage.py makemigrations --check` at the start of `jenkins/entrypoint.sh` would allow to detect such errors when one rebases an open PR before merge and update migrations accordingly

**Comment by yakky** [comment]
Closing this because I pushed an extra commit that shouldn't be there. I will reopen using a clean commit

**Pull request closed without merging**
