### PR TITLE
#3653 adds a new field that allows repository managers to provide additional help text for the preprint update page.

### LINKED ISSUE #3653: Preprints: New version "Help" box should support custom text
**Is your feature request related to a problem? Please describe.**
 As a preprints repository moderator or admin, I expect to provide explicit instruction to submitting authors about the requirements for new versions of their preprint in the "Help" box. Currently preprint repositories are unable to edit this text.

image

**Describe the solution you'd like**
 Add to the new version template the ability to add custom text in the "Help" box, similar to the request for custom text on Page 3 of the submission workflow (https://github.com/BirkbeckCTP/janeway/issues/3404 ). 

It would also be nice to have a link to "Review submission requirements" which opens a popup or modal widow which displays the same requirements text as displayed in Step 1 of the submission start text.

**Additional context**
Uncertain whether the changes in Page 3 of the submission workflow in https://github.com/BirkbeckCTP/janeway/pull/3479 (for feature request https://github.com/BirkbeckCTP/janeway/issues/3404 ) already address the issue.

### PR DESCRIPTION
**Pull request by ajrbyers**
- In line with other additional help text changes this PR adds a new rich text field that lets repository managers provide additional help text to authors when they are submitting a submission update.
- Closes #3653

### CODE REVIEW

**Comment by joemull** [comment]
@ajrbyers I just saw this when checking for PRs needing reviewing on the 1.6 board. It's been there for a while but doesn't have any reviewers requested. Did you mean to request some?

**Comment by ajrbyers** [comment]
Holding this PR until https://github.com/BirkbeckCTP/janeway/pull/3983 is merged.

**Review by mauromsl — APPROVED** [review]

**Review by joemull — COMMENTED** [review]
I think I'm missing context again @ajrbyers and I don't see any comments about this: why are we putting this through for review with the Summernote widget? Wouldn't we want to use TinyMCE for new fields? And shouldn't it be bleached?

**Comment by ajrbyers** [comment]
> I think I'm missing context again @ajrbyers and I don't see any comments about this: why are we putting this through for review with the Summernote widget? Wouldn't we want to use TinyMCE for new fields? And shouldn't it be bleached?

Reckon I added the reviewers as a impulse, though its no longer on hold and I can sort this post merging of the other PR.

**Review by joemull — CHANGES_REQUESTED** [review]
> Reckon I added the reviewers as a impulse, though its no longer on hold and I can sort this post merging of the other PR.

OK, sounds good.

**Review by mauromsl — APPROVED** [review]

**Review by mauromsl — CHANGES_REQUESTED** [review]
Changes look good, but it is worth rebasing and considering BleachField + TinyMCE

**Comment by ajrbyers** [comment]
Closed in favour of https://github.com/BirkbeckCTP/janeway/pull/4075

**Pull request closed without merging**
