### PR TITLE
Revisions to Janeway documentation

### PR DESCRIPTION
**Pull request by joemull**
This branch has a bunch of small changes that Siobhan has made to the docs.

## Original description

@S-Haime I am opening a draft pull request for this just so that I can better look at the Git differences and figure out how to form the initial RST merge of workflow guides, as discussed last week.

Also here is an [HTML build from 2024-03-18](https://birkbeckuol.sharepoint.com/:u:/r/sites/ac-ts-arts-olh/Shared%20Documents/General/Janeway/Documentation/docs-update-html-build-2024-03-18.zip?csf=1&web=1&e=vk1XBe) so you can see the rendered RST. This includes the fixes from #4037. Just download and unzip the zip folder and then open the file `index.html` in a browser and it should look and act nearly just like janeway.readthedocs.io.

### CODE REVIEW

**Review by mauromsl — APPROVED** [review]

**Comment by joemull** [comment]
@mauromsl and @ajrbyers I don't think this is ready for review, unless I am out of the loop on the latest plan. It needs a bunch of small fixes from #4037 first. Can we talk about it before merging?

**Comment by ajrbyers** [comment]
Sure thing @joemull. This PR has draft in the title but might be worth marking it as a draft PR.

**Comment by joemull** [comment]
@ajrbyers that's why I mention it -- Mauro changed it from draft to ready last week.

**Comment by joemull** [comment]
OK @ajrbyers, it should be ready now.

**Review by ajrbyers — APPROVED** [review]
This looks good, but there _is_ a conflict in installation.md.

**Pull request merged**
