### PR TITLE
Fix misspellings under Competing Interests

### LINKED ISSUE #1268: Misspellings under Competing Interests
**Describe the bug**
Under "Competing Interests" on the Submission page:

"If you have any competing or conflictof insterests in the publication of this article please state them here."
See no space in "conflictof" and misspelling of "insterests"

**Janeway version**
1.3.5n

**To Reproduce**
1. Go to '/submit/start/'
2. Scroll down to 'Competing Interests'
3 See error

### PR DESCRIPTION
**Pull request by mvpowers**
This fixes #1268

### CODE REVIEW

**Comment by Bbkctp** [comment]
Can one of the admins verify this patch?

**Comment by ajrbyers** [comment]
Verify this

**Comment by ajrbyers** [comment]
Test this please

**Comment by ajrbyers** [comment]
Thanks @mvpowers

**Pull request merged**
