### PR TITLE
AWS Linux 2 Setup Script

### PR DESCRIPTION
**Pull request by amardesi**

### CODE REVIEW

**Comment by Bbkctp** [comment]
Can one of the admins verify this patch?

**Comment by amardesi** [comment]
Just also added a minor fix to default theme ` [0d38279](/BirkbeckCTP/janeway/pull/873/commits/0d3827959a8367ff11966dc6c1bfe9a8320c9041)`

**Comment by ajrbyers** [comment]
test this please

**Comment by ajrbyers** [comment]
Looks good!

**Comment by amardesi** [comment]
Any reason this hasn't been merged into master?

**Comment by mauromsl** [comment]
No particular reason, I think this was mistakenly merged into the 1.3.2 branch after having finished working on 1.3.2.
Merged into master

**Pull request merged**
